name: Dulguun Enkhzaya
title: Portfolio
logo: /images/headshot.jpg
description: I have recently completed a Master's degree in International Business and am currently seeking full-time remote opportunities as a Business Analyst, Market Researcher, or Business Strategist.
theme: jekyll-theme-minimal
