name: Dulguun Enkhzaya
title: Dulguun Enkhzaya
logo: /images/headshot.jpg
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
theme: jekyll-theme-minimal
